// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PorscheDealership.Data;

#nullable disable

namespace PorscheDealership.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250301171221_SeedCarsData")]
    partial class SeedCarsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PorscheDealership.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BodyType = "Coupe",
                            FuelType = "Gasoline",
                            Model = "Porsche 911",
                            Price = 1200000m,
                            Year = 2023
                        },
                        new
                        {
                            ID = 2,
                            BodyType = "SUV",
                            FuelType = "Diesel",
                            Model = "Porsche Cayenne",
                            Price = 900000m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 3,
                            BodyType = "Sedan",
                            FuelType = "Electric",
                            Model = "Porsche Taycan",
                            Price = 1000000m,
                            Year = 2024
                        },
                        new
                        {
                            ID = 4,
                            BodyType = "Sedan",
                            FuelType = "Hybrid",
                            Model = "Porsche Panamera",
                            Price = 1100000m,
                            Year = 2023
                        },
                        new
                        {
                            ID = 5,
                            BodyType = "SUV",
                            FuelType = "Gasoline",
                            Model = "Porsche Macan",
                            Price = 800000m,
                            Year = 2023
                        },
                        new
                        {
                            ID = 6,
                            BodyType = "Coupe",
                            FuelType = "Gasoline",
                            Model = "Porsche 718 Cayman",
                            Price = 700000m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 7,
                            BodyType = "Convertible",
                            FuelType = "Gasoline",
                            Model = "Porsche 718 Boxster",
                            Price = 750000m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 8,
                            BodyType = "Coupe",
                            FuelType = "Hybrid",
                            Model = "Porsche 918 Spyder",
                            Price = 15000000m,
                            Year = 2015
                        },
                        new
                        {
                            ID = 9,
                            BodyType = "Coupe",
                            FuelType = "Gasoline",
                            Model = "Porsche Carrera GT",
                            Price = 20000000m,
                            Year = 2004
                        },
                        new
                        {
                            ID = 10,
                            BodyType = "Coupe",
                            FuelType = "Gasoline",
                            Model = "Porsche 959",
                            Price = 17000000m,
                            Year = 1986
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
