-- MySQL Script generated by MySQL Workbench
-- Пт 06 окт 2023 13:09:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `group_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faculty` (
  `faculty_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`science_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`science_degree` (
  `science_degree_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`science_degree_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher_rank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher_rank` (
  `teacher_rank_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacher_rank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `teacher_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `phone` DECIMAL(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `science_degree_science_degree_id` INT NOT NULL,
  `department_department_id` INT NOT NULL,
  `teacher_rank_teacher_rank_id` INT NOT NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `fk_teacher_science_degree1_idx` (`science_degree_science_degree_id` ASC) VISIBLE,
  INDEX `fk_teacher_department1_idx` (`department_department_id` ASC) VISIBLE,
  INDEX `fk_teacher_teacher_rank1_idx` (`teacher_rank_teacher_rank_id` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_science_degree1`
    FOREIGN KEY (`science_degree_science_degree_id`)
    REFERENCES `mydb`.`science_degree` (`science_degree_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_department1`
    FOREIGN KEY (`department_department_id`)
    REFERENCES `mydb`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_teacher_rank1`
    FOREIGN KEY (`teacher_rank_teacher_rank_id`)
    REFERENCES `mydb`.`teacher_rank` (`teacher_rank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topic` (
  `topic_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `teacher_teacher_id` INT NOT NULL,
  PRIMARY KEY (`topic_id`, `teacher_teacher_id`),
  INDEX `fk_topic_teacher1_idx` (`teacher_teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_teacher1`
    FOREIGN KEY (`teacher_teacher_id`)
    REFERENCES `mydb`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `group_group_id` INT NOT NULL,
  `faculty_faculty_id` INT NOT NULL,
  `topic_topic_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `topic_topic_id`),
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC) VISIBLE,
  INDEX `fk_student_group_idx` (`group_group_id` ASC) VISIBLE,
  INDEX `fk_student_faculty1_idx` (`faculty_faculty_id` ASC) VISIBLE,
  INDEX `fk_student_topic1_idx` (`topic_topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_group`
    FOREIGN KEY (`group_group_id`)
    REFERENCES `mydb`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_faculty1`
    FOREIGN KEY (`faculty_faculty_id`)
    REFERENCES `mydb`.`faculty` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_topic1`
    FOREIGN KEY (`topic_topic_id`)
    REFERENCES `mydb`.`topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grade` (
  `grade_id` INT NOT NULL,
  `exam` INT NOT NULL,
  `diploma` INT NOT NULL,
  `student_student_id` INT NOT NULL,
  PRIMARY KEY (`grade_id`, `student_student_id`),
  INDEX `fk_grade_student1_idx` (`student_student_id` ASC) VISIBLE,
  CONSTRAINT `fk_grade_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
