-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 19:54:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`students_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students_group` (
  `group_id` INT NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `full_name` VARCHAR(45) NULL,
  `year` INT NULL,
  `group_id` INT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_students_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_students_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`students_group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contract` (
  `contract_id` INT NOT NULL,
  `company` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contract_copy1_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_copy1_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `scholarship` INT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`session_result` (
  `semester` INT NOT NULL,
  `student_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`semester`, `student_id`),
  INDEX `fk_session_result_copy1_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_session_result_copy1_category_copy11_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_result_copy1_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_result_copy1_category_copy11`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
